In [1]:
import torch


In [2]:
x = torch.empty(2, 2, 3)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [3]:
x = torch.rand(2, 3)
print(x)

tensor([[0.1884, 0.2242, 0.9673],
        [0.1934, 0.6796, 0.3371]])


In [4]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x.size())
print(x)

torch.Size([2, 2])
tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [5]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [6]:
# Arithmetic operations
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)
z = x + y
print(z)
# function_name with end endscore works in-place
y.add_(x)
print(y)

tensor([[0.8915, 0.2833],
        [0.4532, 0.1863]])
tensor([[0.3323, 0.7259],
        [0.0657, 0.5827]])
tensor([[1.2238, 1.0092],
        [0.5189, 0.7690]])
tensor([[1.2238, 1.0092],
        [0.5189, 0.7690]])


In [7]:
# Slicing
x = torch.rand(5, 3)
print(x)
print(x[:, 0])

tensor([[0.7470, 0.5206, 0.4395],
        [0.3215, 0.4549, 0.5275],
        [0.2475, 0.6546, 0.7011],
        [0.2295, 0.4586, 0.2794],
        [0.0194, 0.4482, 0.5574]])
tensor([0.7470, 0.3215, 0.2475, 0.2295, 0.0194])


In [8]:
# Reshaping
x = torch.rand(4, 4)
print(x)
# -1 implicitly specify other dimension
y = x.view(-1, 8)
print(y)

tensor([[0.3931, 0.0771, 0.0913, 0.0270],
        [0.4471, 0.5652, 0.0533, 0.2804],
        [0.0184, 0.8498, 0.2167, 0.5321],
        [0.9941, 0.7230, 0.9937, 0.2028]])
tensor([[0.3931, 0.0771, 0.0913, 0.0270, 0.4471, 0.5652, 0.0533, 0.2804],
        [0.0184, 0.8498, 0.2167, 0.5321, 0.9941, 0.7230, 0.9937, 0.2028]])


In [9]:
# Conversion to numpy array
import numpy as np
a = torch.ones(5)
print(a)
b = a.numpy()
print(type(b))
print(b)
# Mind the same memory location
#a and b point to the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [10]:
print(torch.cuda.is_available())
if torch.cuda.is_available():
  device = torch.device("cuda")
  x = torch.ones(5, device=device)
  y = torch.ones(5)
  y = y.to(device)
  z = x + y
  # Gives an error, to_numpy() works only with cpu
  #print(z.numpy())
  z = z.to("cpu")
  #print(z.numpy())

False


In [11]:
x = torch.ones(5, requires_grad=True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)
