In [1]:
# Autograd Gradient Calculations
import torch
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.7576,  3.0202,  0.7436], requires_grad=True)


In [2]:
y = x + 2 # sum((x + 2))^2 * 2)/n == 4 * (x + 2)/n
print(y)
z = y * y * 2 # sum(y^2 * 2)/n
print(z)
z = z.mean() #sum(z)/n
print(z)

tensor([1.2424, 5.0202, 2.7436], grad_fn=<AddBackward0>)
tensor([ 3.0870, 50.4043, 15.0551], grad_fn=<MulBackward0>)
tensor(22.8488, grad_fn=<MeanBackward0>)


In [3]:
z.backward() # dz/dx
print(x.grad)

tensor([1.6565, 6.6936, 3.6582])


In [4]:
# Prevent tracking gradients
# x.requires_grad(False)
#x.detach()
# with torch.no_grad()

In [5]:
y = x.detach()
print(y)

tensor([-0.7576,  3.0202,  0.7436])


In [6]:
with torch.no_grad():
    y = x + 2
    print(y)

tensor([1.2424, 5.0202, 2.7436])


In [7]:
# gradients are accumulating
weights = torch.ones(4, requires_grad=True)

In [8]:
for epoch in range(1):
    model_output = (weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])


In [9]:
#optimazer = torch.optim.SGD(weights, lr=0.01)
#optimazer.step()
#optimazer.zero_grad()